const TRANSLATE_BASE_URL = import.meta.env.VITE_GOOGLE_TRANSLATE_BASE_URL;
const GOOGLE_TRANSLATE_API_KEY = import.meta.env.VITE_GOOGLE_TRANSLATE_API_KEY;

export { TRANSLATE_BASE_URL, GOOGLE_TRANSLATE_API_KEY };
